ALTER TABLE funds
ADD COLUMN IF NOT EXISTS provider VARCHAR(50) DEFAULT 'TSETMC';

ALTER TABLE funds
ADD COLUMN IF NOT EXISTS symbol VARCHAR(100);

ALTER TABLE funds
ADD COLUMN IF NOT EXISTS sector VARCHAR(255);

ALTER TABLE funds
ADD COLUMN IF NOT EXISTS subsector VARCHAR(255);

ALTER TABLE funds
ADD COLUMN IF NOT EXISTS market VARCHAR(100);

ALTER TABLE funds
ADD COLUMN IF NOT EXISTS instrument_status VARCHAR(100);

ALTER TABLE etf_market
ADD COLUMN IF NOT EXISTS provider VARCHAR(50) DEFAULT 'TSETMC';

ALTER TABLE etf_market
ADD COLUMN IF NOT EXISTS sector VARCHAR(255);

ALTER TABLE etf_market
ADD COLUMN IF NOT EXISTS subsector VARCHAR(255);

ALTER TABLE etf_market
ADD COLUMN IF NOT EXISTS market VARCHAR(100);

ALTER TABLE etf_market
ADD COLUMN IF NOT EXISTS instrument_status VARCHAR(100);
