ALTER TABLE funds
ADD COLUMN IF NOT EXISTS portfolio_cash DOUBLE PRECISION;

ALTER TABLE funds
ADD COLUMN IF NOT EXISTS portfolio_other DOUBLE PRECISION;

ALTER TABLE funds
ADD COLUMN IF NOT EXISTS ins_code VARCHAR(32);

ALTER TABLE funds
ADD COLUMN IF NOT EXISTS is_etf VARCHAR(10) DEFAULT 'false';
