ALTER TABLE funds
ALTER COLUMN is_etf DROP DEFAULT;

ALTER TABLE funds
ALTER COLUMN is_etf TYPE BOOLEAN
USING (
    CASE
        WHEN LOWER(is_etf) = 'true' THEN TRUE
        ELSE FALSE
    END
);

ALTER TABLE funds
ALTER COLUMN is_etf SET DEFAULT FALSE;

ALTER TABLE funds
ALTER COLUMN is_etf SET NOT NULL;
